### ISSUE TITLE
Show a welcome popup to user when they visit for the first time.

### ISSUE THREAD

**Issue by ishaanbedi** [ishaanbedi/webnotes#1]
When a user visit webnotes for the first time, it is essential to provide an informative experience to guide them through the platform and tell a bit about the features. 

To achieve this, we must implement a **_Welcome Popup_** feature that will appear only on the user's initial visit that mentions a few features about the app (refer to the About section in the navbar of the app) and provide a link to the GitHub repo.

We are using [DaisyUI](https://daisyui.com/) which provides [modal](https://daisyui.com/components/modal/) out of the box to integrate into the application, so it'll be easy to work upon the issue.

To track recurring visits of the user and to show the popup for the first time only, use [localStorage APIs](https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage) and toggle the visibility after the user first interacts with the modal.

**Comment by dipushrestha** [comment]
Hi @ishaanbedi, I would like to work on this.

**Comment by ishaanbedi** [comment]
Hey @dipushrestha ! 
Assigned it to you. 
Hit me up if you face any issues or require more information at any point in time.

**Comment by dipushrestha** [comment]
@ishaanbedi, I have raised a PR. Please have a look at it.

Also, can you add `hacktoberfest` topic to this repo?
![image](https://github.com/ishaanbedi/webnotes/assets/36785868/90876fdd-f2b6-4dbb-8e47-2d468c23aa8f)

**Comment by ishaanbedi** [comment]
> @ishaanbedi, I have raised a PR. Please have a look at it.

Works brilliantly, @dipushrestha !

Thank you for your valuable contribution. 

> Also, can you add hacktoberfest topic to this repo?

I've updated the label on the repo as well as in your PR. Care to re-check? 

Please update me if the status changes to participating or not.

Best,
Ishaan

**Comment by dipushrestha** [comment]
> Please update me if the status changes to participating or not.

Now, it has changed to participating. Thank you!
![image](https://github.com/ishaanbedi/webnotes/assets/36785868/0779386a-ffa0-4d7f-834c-ab61600d34ab)
