### ISSUE TITLE
Provide proper setup instructions to use as offline app.

### ISSUE THREAD

**Issue by ishaanbedi** [ishaanbedi/webnotes#3]
Webnotes is configured as a PWA application, so users can install it on their devices and work offline as well, but currently, the user is not being prompted/shown instructions to install it locally or steps to install it locally and work in an offline mode.

Looking forward to creating a button in the navbar, that prompts the user with some steps to install it locally (clicking the Chrome menu button and adding to the home screen etc).

To make it simple, use the following components from [DaisyUI](https://daisyui.com/) itself:
- [Button](https://daisyui.com/components/button/)
- [Modal](https://daisyui.com/components/modal/)
- [Range](https://daisyui.com/components/range/)

**Comment by code-with-ryan** [comment]
Hi, I would be glad to help with this.

**Comment by ishaanbedi** [comment]
@code-with-ryan 
Assigned! Good luck!
