### ISSUE TITLE
Remove yarn.lock or package-lock.json file from the repo

### ISSUE THREAD

**Issue by dipushrestha** [ishaanbedi/webnotes#5]
Currently, this project has both `yarn.lock` and `package-lock.json` files. We should only use either of these files and standardize the use with one package manager.

**Comment by ishaanbedi** [comment]
Yeah, you are absolutely right. 

I migrated to yarn in the middle of developing this project back then, and I totally forgot to delete the package-lock.json file, although on my local setup, and on Vercel, the build takes place using yarn only, so package-lock.json is pretty much useless and is never utilized anywhere.

If you want, you can open a PR that closes this issue by deleting it, or I will manually remove the file in a later commit.

Thanks for bringing this up!
