### ISSUE TITLE
The page has overflow horizontally

### ISSUE THREAD

**Issue by Famozzy** [ishaanbedi/webnotes#7]
### Screenshot
![image](https://github.com/ishaanbedi/webnotes/assets/41115929/cc94118d-b89a-48f6-aefa-499609a1071d)

**Comment by Famozzy** [comment]
I can fix that, kindly assign me

**Comment by ishaanbedi** [comment]
@Famozzy Assigned! Good luck.

**Comment by Famozzy** [comment]
thanks, I will working on it
